### ISSUE TITLE
Make progressbar window movable

### ISSUE THREAD

**Issue by ThePhilgrim** [ThePhilgrim/N-Trans#22]
The progress bar window doesn't have the top bar with X, minimize, maximize. Therefore, it's not currently movable. Fix it ..

**Comment by Akuli** [comment]
While you're at it, consider renaming `ProgressBar` to `ProgressWindow`, since it's not just a progress bar. It's an entire window.

**Comment by ThePhilgrim** [comment]
Decided to put the progress bar in the main GUI window.
